server:
  port: 7070

spring:
  application:
    name: migration-study

  datasource:
    url: jdbc:h2:mem:szs;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 1234

  ### URL: http://localhost:7070/h2-console ###
  h2:
    console:
      path: /h2-console
      enabled: true

  graphql:
    graphiql:
      enabled: true
      printer:
        enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG        # 실행된 SQL 쿼리를 출력
        type: trace       # 쿼리에 바인딩된 파라미터를 출력
      springframework:
        jdbc:
          datasource:
            init: DEBUG   # 데이터 초기화 관련 로그 출력